const { initializeDatabase, closeDatabase, db } = require('./testModelsSetup'); 
//const db = require('../../testIndex');

describe('Country Model Tests', () => {
    beforeAll(async () => {
        //console.log("########## beforeAll ########## calling db.syncronizeAndMigrate now.");
        //await db.synchronizeAndMigrate();
        await initializeDatabase();
    });     

    afterAll(async () => {
        await closeDatabase();
        // await db.sequelize.close();
        // console.log('Database connection closed');
    });


    // Basic tests for creating, updating, deleting, and retrieving data
    test('Create a valid Country', async () => {
        // Test for creating a new country instance
        const country = await db.Country.create({ countryCode: 'US', countryName: 'United States' });
        expect(country.countryCode).toBe('US');
        expect(country.countryName).toBe('United States');
    });

    // test('Fail to create a Country with invalid data', async () => {
    //     // Test for handling invalid data (e.g., missing countryCode or countryName)
    //     await expect(db.Country.create({ countryName: null })).rejects.toThrow(); // Assuming countrName is required
    //     await expect(db.Country.create({ countryCode: null })).rejects.toThrow(); // Assuming countryCode is required
    // });

    
    // Association tests

    // // Testing associations can be a bit more complex, as it often requires
    // // setting up related data in other tables.

    // test('Country and Asin Association', async () => {
    //     // Assuming Asin model is related and you have already set up some test data
    //     const country = await Country.findByPk('US');
    //     const asins = await country.getAsins(); // GetAsins method is automatically generated by Sequelize

    //     // Check if the associated data is correct
    //     expect(asins.length).toBeGreaterThan(0); // Assuming there are related ASINs
    //     expect(asins[0].countryCode).toBe('US');
    // });

});





