const modelToFileMap = {
  Asin: 'asins.csv',
  AsinSku: 'asins_skus.csv',
  Brand: 'brands.csv',
  VatCategory: 'vat_categories.csv',
  Country: 'countries.csv',
  Ean: 'eans.csv',
  ProductCategoryRank: 'product_categories_ranks.csv',
  ProductCategory: 'product_categories.csv',
  ProductTaxCategory: 'product_tax_categories.csv',
  Sku: 'skus.csv',
  VatRatePerCountry: 'vat_rates_per_country.csv',
  EanInAsin: 'eans_in_asins.csv',
  Warehouse: 'warehouses.csv',
  AmazonReferralFee: 'amazon_referral_fees.csv',
  ProductAndAmzReferralFeeCategory:
    'product_and_amz_referral_fees_categories.csv',
  PriceGridFbaFee: 'price_grid_fba_fees.csv',
  PricingRule: 'pricing_rules.csv',
  Supplier: 'suppliers.csv',
  Donation: 'donations.csv',
  SupplierOrder: 'suppliers_orders.csv',
  MinimumSellingPrice: 'minimum_selling_prices.csv',
  FbaFee: 'fba_fees.csv',
  Catalog: 'catalog.csv',
  SupplierBrandCatalog: 'suppliers_brands_catalog.csv',
  EanInSupplierOrder: 'eans_in_suppliers_orders.csv',
  EanInDonation: 'eans_in_donations.csv',
  WarehouseStock: 'warehouses_stock.csv',
};

module.exports = modelToFileMap;
